version: '3.8'

services:
  app:
    build: .
    ports:
      - "5432:5432"
    environment:
      - DATASOURCE_URL=jdbc:postgresql://localhost:5432/Customer_Data_Management
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=1234
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pass@1234
      POSTGRES_DB: customer_data_management
    ports:
      - "5432:5432"