micronaut:
  application:
    name: customerDataManagement
  server:
    port: 8080
    cors:
      enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  validator:
    enabled: false
datasources:
  default:
    driverClassName: org.postgresql.Driver
    db-type: postgres
    url: jdbc:postgresql://ep-quiet-meadow-a14vpajc.ap-southeast-1.pg.koyeb.app/Customer_Data_Management
    username: admin
    password: npg_4GLP1VUosSaE
    dialect: POSTGRES
netty:
  default:
    allocator:
      max-order: 3
jpa:
  default:
    entity-scan:
      packages: com.dm.customer.model
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        hbm2ddl:
          auto: update
        show_sql: true